// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: HUD

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t *ui_MainScreen;
lv_obj_t *ui_RootPanel;
lv_obj_t *ui_TopPanel;
lv_obj_t *ui_Title;
lv_obj_t *ui_SpeedPanel;
lv_obj_t *ui_SpeedBG;
lv_obj_t *ui_SpeedSlider;
lv_obj_t *ui_MinSpeed;
lv_obj_t *ui_MaxSpeed;
lv_obj_t *ui_UnitLabel;
lv_obj_t *ui_SpeedLabel;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_drawing[1] = {&ui_img_drawing1_png};
const lv_img_dsc_t *ui_imgset_final[2] = {&ui_img_final1_png, &ui_img_final11_png};
const lv_img_dsc_t *ui_imgset_473009053[1] = {&ui_img_189200015};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_MainScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_MainScreen);
}
