// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: HUD

#ifndef _HUD_UI_H
#define _HUD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif
#include <lvgl.h>
#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t *ui_MainScreen;
extern lv_obj_t *ui_RootPanel;
extern lv_obj_t *ui_TopPanel;
extern lv_obj_t *ui_Title;
extern lv_obj_t *ui_SpeedPanel;
extern lv_obj_t *ui_SpeedBG;
extern lv_obj_t *ui_SpeedSlider;
extern lv_obj_t *ui_MinSpeed;
extern lv_obj_t *ui_MaxSpeed;
extern lv_obj_t *ui_UnitLabel;
extern lv_obj_t *ui_SpeedLabel;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_speedbg_png);   // assets\speedBG.png
LV_IMG_DECLARE( ui_img_speedfg_png);   // assets\speedFG.png
LV_IMG_DECLARE( ui_img_drawing1_png);   // assets\drawing1.png
LV_IMG_DECLARE( ui_img_final1_png);   // assets\final1.png
LV_IMG_DECLARE( ui_img_final11_png);   // assets\final11.png
LV_IMG_DECLARE( ui_img_189200015);   // assets\futuristic-car-speedometer-digital-gauge-dial_8071-13242.png

LV_FONT_DECLARE( ui_font_Display16);
LV_FONT_DECLARE( ui_font_Display24);
LV_FONT_DECLARE( ui_font_Display20);
LV_FONT_DECLARE( ui_font_Display70);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
