// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: HUD

#include <lvgl.h>
#include "ui.h"
//int currentSpeed;

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RootPanel = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_RootPanel, 320);
lv_obj_set_height( ui_RootPanel, 240);
lv_obj_set_x( ui_RootPanel, 0 );
lv_obj_set_y( ui_RootPanel, -1 );
lv_obj_set_align( ui_RootPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_RootPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RootPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RootPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RootPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_RootPanel, lv_color_hex(0x0EE9F0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_RootPanel, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RootPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TopPanel = lv_obj_create(ui_RootPanel);
lv_obj_set_width( ui_TopPanel, 140);
lv_obj_set_height( ui_TopPanel, 50);
lv_obj_set_x( ui_TopPanel, -2 );
lv_obj_set_y( ui_TopPanel, -20 );
lv_obj_set_align( ui_TopPanel, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_TopPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TopPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TopPanel, lv_color_hex(0x1BD7EA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TopPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_TopPanel, lv_color_hex(0xEE112E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_TopPanel, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TopPanel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TopPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TopPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_TopPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_TopPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_TopPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_TopPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_TopPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Title = lv_label_create(ui_TopPanel);
lv_obj_set_width( ui_Title, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Title, LV_ALIGN_CENTER );
lv_label_set_text(ui_Title,"SPEEDOMETER");
lv_obj_set_style_text_font(ui_Title, &ui_font_Display24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedPanel = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_SpeedPanel, lv_pct(100));
lv_obj_set_height( ui_SpeedPanel, lv_pct(65));
lv_obj_set_align( ui_SpeedPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SpeedPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SpeedPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SpeedPanel, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SpeedPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_SpeedPanel, lv_color_hex(0x0EE9F0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_SpeedPanel, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SpeedPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedBG = lv_img_create(ui_SpeedPanel);
lv_img_set_src(ui_SpeedBG, &ui_img_speedbg_png);
lv_obj_set_width( ui_SpeedBG, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SpeedBG, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SpeedBG, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SpeedBG, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_SpeedBG, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SpeedSlider = lv_slider_create(ui_SpeedBG);
lv_slider_set_range(ui_SpeedSlider, 0,130);
lv_slider_set_value( ui_SpeedSlider, 120, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SpeedSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SpeedSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SpeedSlider, 320);
lv_obj_set_height( ui_SpeedSlider, 140);
lv_obj_set_align( ui_SpeedSlider, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_SpeedSlider, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SpeedSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SpeedSlider, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_SpeedSlider, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SpeedSlider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SpeedSlider, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_SpeedSlider, &ui_img_speedfg_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );

lv_obj_set_style_radius(ui_SpeedSlider, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SpeedSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SpeedSlider, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_MinSpeed = lv_label_create(ui_SpeedBG);
lv_obj_set_width( ui_MinSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MinSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MinSpeed, 19 );
lv_obj_set_y( ui_MinSpeed, -4 );
lv_obj_set_align( ui_MinSpeed, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_MinSpeed,"0");
lv_obj_set_style_text_color(ui_MinSpeed, lv_color_hex(0xF8F4F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MinSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MinSpeed, &ui_font_Display24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MaxSpeed = lv_label_create(ui_SpeedBG);
lv_obj_set_width( ui_MaxSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MaxSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MaxSpeed, -15 );
lv_obj_set_y( ui_MaxSpeed, -1 );
lv_obj_set_align( ui_MaxSpeed, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_MaxSpeed,"130");
lv_obj_set_style_text_color(ui_MaxSpeed, lv_color_hex(0xF8F4F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MaxSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MaxSpeed, &ui_font_Display24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UnitLabel = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_UnitLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_UnitLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_UnitLabel, 120 );
lv_obj_set_y( ui_UnitLabel, 66 );
lv_obj_set_align( ui_UnitLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_UnitLabel,"KM/H");
lv_obj_set_style_text_color(ui_UnitLabel, lv_color_hex(0xF9F3F3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_UnitLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_UnitLabel, &ui_font_Display24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedLabel = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_SpeedLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SpeedLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SpeedLabel, 48 );
lv_obj_set_y( ui_SpeedLabel, 49 );
lv_obj_set_align( ui_SpeedLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SpeedLabel,"100");
lv_obj_set_style_text_color(ui_SpeedLabel, lv_color_hex(0x3DF00E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SpeedLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SpeedLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SpeedLabel, &ui_font_Display70, LV_PART_MAIN| LV_STATE_DEFAULT);

}
